export const PARANOIA = {
  attributes: {
    strength: 'PARANOIA.AttributeStr',
    constitution: 'PARANOIA.AttributeCon',
    agility: 'PARANOIA.AttributeAgi',
    dexterity: 'PARANOIA.AttributeDex',
    perception: 'PARANOIA.AttributePer',
    cynicism: 'PARANOIA.AttributeCyn',
    mechanics: 'PARANOIA.AttributeMec',
    power: 'PARANOIA.AttributePower',
  },
  attributeAbbreviations: {
    strength: 'PARANOIA.AttributeStrAbbr',
    constitution: 'PARANOIA.AttributeConAbbr',
    agility: 'PARANOIA.AttributeAgiAbbr',
    dexterity: 'PARANOIA.AttributeDexAbbr',
    perception: 'PARANOIA.AttributePerAbbr',
    cynicism: 'PARANOIA.AttributeCynAbbr',
    mechanics: 'PARANOIA.AttributeMecAbbr',
    power: 'PARANOIA.AttributePowerAbbr',
  },
  skills: {
    ancientBladeWeapons: 'PARANOIA.SkillAncientBladeWeapons',
    energyBlade: 'PARANOIA.SkillEnergyBlade',
    grenades: 'PARANOIA.SkillGrenades',
    neuroWhip: 'PARANOIA.SkillNeuroWhip',
    fight: 'PARANOIA.SkillFight',
    fightBaton: 'PARANOIA.SkillFightBaton',
    charm: 'PARANOIA.SkillCharm',
    charlatanery: 'PARANOIA.SkillCharlatanery',
    lying: 'PARANOIA.SkillLying',
    forgery: 'PARANOIA.SkillForgery',
    interrogation: 'PARANOIA.SkillInterrogation',
    intimidation: 'PARANOIA.SkillIntimidation',
    falseLogic: 'PARANOIA.SkillFalseLogic',
    oratory: 'PARANOIA.SkillOratory',
    psychology: 'PARANOIA.SkillPsychology',
    bribery: 'PARANOIA.SkillBribery',
    suggestion: 'PARANOIA.SkillSuggestion',
    ancientThrowWeapons: 'PARANOIA.SkillAncientThrowWeapons',
    projectilEnergyLaserWar: 'PARANOIA.SkillProjectilEnergyLaserWar',
    vehicleWeapons: 'PARANOIA.SkillVehicleWeapons',
    warVehicleWeapons: 'PARANOIA.SkillWarVehicleWeapons',
    missiles: 'PARANOIA.SkillMissiles',
    mechanics: 'PARANOIA.SkillMechanics',
    engineering: 'PARANOIA.SkillEngineering',
    robotics: 'PARANOIA.SkillRobotics',
    dataAnalysis: 'PARANOIA.SkillDataAnalysis',
    bioEngineering: 'PARANOIA.SkillBioEngineering',
    bioChemistry: 'PARANOIA.SkillBioChemistry',
    dataSearch: 'PARANOIA.SkillDataSearch',
    demolition: 'PARANOIA.SkillDemolition',
    nuclearPhysics: 'PARANOIA.SkillNuclearPhysics',
    mechanicEngineering: 'PARANOIA.SkillMechanicEngineering',
    medicine: 'PARANOIA.SkillMedicine',
    chemistry: 'PARANOIA.SkillChemistry',
    security: 'PARANOIA.SkillSecurity',
    survival: 'PARANOIA.SkillSurvival',
    surveillance: 'PARANOIA.SkillSurveillance',
  },

  damageLabels: {
    SE: 'PARANOIA.DamageLabels.SE',
    A: 'PARANOIA.DamageLabels.A',
    H: 'PARANOIA.DamageLabels.H',
    I: 'PARANOIA.DamageLabels.I',
    M: 'PARANOIA.DamageLabels.M',
    V: 'PARANOIA.DamageLabels.V',
  },
}
